In [1]:
import matplotlib.pyplot as plt
import numpy as np



In [2]:
rng = np.random.RandomState(42)
x = 10 * rng.rand(50)
y = 2 * x - 1 + rng.randn(50)
plt.scatter(x, y);

In [7]:
x.shape

(50,)

In [5]:
from sklearn.linear_model import LinearRegression
model = LinearRegression(fit_intercept=True)
model

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [8]:
# we need to massage the data x to make it a matrix of size [n_samples, n_features]
X = x[:, np.newaxis]
X.shape

(50, 1)

In [9]:
X

array([[ 3.74540119],
       [ 9.50714306],
       [ 7.31993942],
       [ 5.98658484],
       [ 1.5601864 ],
       [ 1.5599452 ],
       [ 0.58083612],
       [ 8.66176146],
       [ 6.01115012],
       [ 7.08072578],
       [ 0.20584494],
       [ 9.69909852],
       [ 8.32442641],
       [ 2.12339111],
       [ 1.81824967],
       [ 1.8340451 ],
       [ 3.04242243],
       [ 5.24756432],
       [ 4.31945019],
       [ 2.9122914 ],
       [ 6.11852895],
       [ 1.39493861],
       [ 2.92144649],
       [ 3.66361843],
       [ 4.56069984],
       [ 7.85175961],
       [ 1.99673782],
       [ 5.14234438],
       [ 5.92414569],
       [ 0.46450413],
       [ 6.07544852],
       [ 1.70524124],
       [ 0.65051593],
       [ 9.48885537],
       [ 9.65632033],
       [ 8.08397348],
       [ 3.04613769],
       [ 0.97672114],
       [ 6.84233027],
       [ 4.40152494],
       [ 1.22038235],
       [ 4.9517691 ],
       [ 0.34388521],
       [ 9.09320402],
       [ 2.58779982],
       [ 6

In [10]:
model.fit(X, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [11]:
y

array([  7.22926896,  18.18565441,  13.52423055,  10.67206599,
         0.64185082,   1.4000462 ,  -0.29896653,  17.38064514,
        11.36591852,  11.3984114 ,  -0.26422614,  18.01311476,
        14.97193082,   3.8584585 ,   3.66749887,   3.59937032,
         4.24562734,   9.18591626,   7.9701638 ,   5.80012793,
        10.75788366,   1.60421824,   3.736558  ,   5.13103024,
         8.93392551,  16.05975926,   2.92146552,  10.28822167,
        11.2099274 ,  -0.7161115 ,  11.51229264,   3.94851904,
         0.26520582,  19.5423544 ,  15.69289556,  15.98984947,
         5.17932245,   0.65443493,  12.77642131,   5.81548096,
         1.22109281,   9.26065077,   1.16566447,  16.66813782,
         3.36710603,  11.74868864,   6.14962364,   9.73011153,
         9.40444538,   3.21035654])

In [12]:
model.coef_


array([ 1.9776566])

In [13]:
model.intercept_

-0.90331072553111458

In [20]:
xfit = np.linspace(-1, 11)

In [15]:
Xfit = xfit[:, np.newaxis]
yfit = model.predict(Xfit)

In [16]:
plt.scatter(x, y)
plt.plot(xfit, yfit);

In [21]:
xfit

array([ -1.        ,  -0.75510204,  -0.51020408,  -0.26530612,
        -0.02040816,   0.2244898 ,   0.46938776,   0.71428571,
         0.95918367,   1.20408163,   1.44897959,   1.69387755,
         1.93877551,   2.18367347,   2.42857143,   2.67346939,
         2.91836735,   3.16326531,   3.40816327,   3.65306122,
         3.89795918,   4.14285714,   4.3877551 ,   4.63265306,
         4.87755102,   5.12244898,   5.36734694,   5.6122449 ,
         5.85714286,   6.10204082,   6.34693878,   6.59183673,
         6.83673469,   7.08163265,   7.32653061,   7.57142857,
         7.81632653,   8.06122449,   8.30612245,   8.55102041,
         8.79591837,   9.04081633,   9.28571429,   9.53061224,
         9.7755102 ,  10.02040816,  10.26530612,  10.51020408,
        10.75510204,  11.        ])

In [22]:
yfit

array([ -2.88096733,  -2.39664326,  -1.9123192 ,  -1.42799513,
        -0.94367106,  -0.459347  ,   0.02497707,   0.50930113,
         0.9936252 ,   1.47794926,   1.96227333,   2.44659739,
         2.93092146,   3.41524552,   3.89956959,   4.38389366,
         4.86821772,   5.35254179,   5.83686585,   6.32118992,
         6.80551398,   7.28983805,   7.77416211,   8.25848618,
         8.74281024,   9.22713431,   9.71145837,  10.19578244,
        10.68010651,  11.16443057,  11.64875464,  12.1330787 ,
        12.61740277,  13.10172683,  13.5860509 ,  14.07037496,
        14.55469903,  15.03902309,  15.52334716,  16.00767122,
        16.49199529,  16.97631936,  17.46064342,  17.94496749,
        18.42929155,  18.91361562,  19.39793968,  19.88226375,
        20.36658781,  20.85091188])